### ISSUE TITLE
mismatch in documentation/implementation for parameter "2step_output"

### ISSUE THREAD

**Issue by hurzhurz** [privacyidea/privacyidea-authenticator#104]
I don't know which one is correct, but I noticed a mismatch between documentation and implementation for the "2step_output" parameter:

Documentation says it is given in bits:
https://github.com/privacyidea/privacyidea-authenticator/blob/master/doc/README.md#2step_output

But here it gets multiplied by 8, so probably expected to be bytes:
https://github.com/privacyidea/privacyidea-authenticator/blob/master/app/src/main/java/it/netknights/piauthenticator/viewcontroller/MainActivity.java#L402

**Comment by nilsbehlen** [comment]
Hi, thanks for pointing this out. It seems the documentation was not updated (until now), since implementation works.

**Comment by hurzhurz** [comment]
Great that you already updated it! Though I would suggest to also change the example:
`2step_output=160`
to
`2step_output=20`

**Comment by nilsbehlen** [comment]
you're right, fixed it.
