### ISSUE TITLE
no notifications if app is in foreground but screen is locked

### ISSUE THREAD

**Issue by jmozd** [privacyidea/privacyidea-authenticator#106]
During testing the latest (Nov 12 v3.0.7) version of the authenticator app on Android (8.0.0), I noticed that I do not receive push token notifications if the app is in the foreground but the screen is locked.

Steps to reproduce:

- open app
- wait for screen to lock
- create push token request

Expected behavior: 

- Android should signal the request to the user (same as if the app is in the background)

Actual behavior:

- No notification happens at all. User will only recognize new auth request when unlocking the screen.

**Comment by nilsbehlen** [comment]
Hi, thanks for your feedback. This is the repo for the old version that will be archived once the new is officially released.
I created an issue for this in the new repo.
