### ISSUE TITLE
first HOTP token not usable.

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator#12]
The first HOTP token in the list does not have a "Next" button. I.e. I can not generate the next OTP value.

# how to reproduce

clear the token list (all tokens) and scan the QR Code for an HOTP token.

**Comment by nilsbehlen** [comment]
I was not able to reproduce this bug today (tried with emulator).
On my phone the button appears normally, so i have to further look into this

**Comment by cornelinux** [comment]
Maybe we can debug through this on my phone, if you find a sensible way to debug this.

**Comment by cornelinux** [comment]
I can not see this either - anymore.
