### ISSUE TITLE
Make headline the same light blue

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator#2]
Currently the head line of the phone (status line with battery, wifi signal..) is a dark blue.
This should be the same light blue as the default blue color.

**Comment by nilsbehlen** [comment]
The statusbarcolor can only be changed from API 21+ (which is Lollipop).
I added some code to change the color if you're using Lollipop or higher

**Comment by cornelinux** [comment]
Looks nice! :-)
