### ISSUE TITLE
"Invalid QR code" from nextCloud 12.0.3 and Bitbucket

### ISSUE THREAD

**Issue by devurandom** [privacyidea/privacyidea-authenticator#25]
I am running nextCloud 12.0.3. When I enable TOTP in its settings and scan the QR code with privacyIDEA Authenticator 0.1.4 (LineageOS 14.1-20171215-NIGHTLY-serranoltexx, Android 7.1.2), the app replies "invalid QR code".

[Bitbucket](https://bitbucket.org/) has the same issue.

**Comment by cornelinux** [comment]
Which version of the privacyIDEA Authenticator are you running? 
There were issues that were fixed with 0.1.3. The latest is 0.1.4.

Please provide the QR code, that nextCloud generates. Maybe it is indeed invalid.

**Comment by devurandom** [comment]
In addition to nextCloud and Bitbucket, I just also noticed the problem with Coinbase. So far only the first registration I tried worked: Protonmail. They appear to use a larger QR-code.

A failing code, anonymised, is: `otpauth://totp/ISSUER:USERNAME_OR_EMAIL?secret=s1xt33nnumb3rs4ndl3tt3rs&issuer=ISSUER`

**Comment by cornelinux** [comment]
Thanks a lot.

@nilsbehlen It looks like we are requiring the parameter "ditigts" although it is specified as optional in the key uri spec.

See here: https://github.com/privacyidea/privacyidea-authenticator/blob/04c35b1cc9a9c41006d519a2f262bbc401c6d0da/app/src/main/java/it/netknights/piauthenticator/MainActivity.java#L464

THe parameter needs to be optional (see #22). The default is 6 according to the specs.

**Comment by devurandom** [comment]
Thanks, 0.1.5 fixes the issue.
