### ISSUE TITLE
"Add token manually" menu renders badly

### ISSUE THREAD

**Issue by devurandom** [privacyidea/privacyidea-authenticator#26]
The "add token manually" menu of privacyIDEA Authenticator 0.1.4 renders badly on my device (LineageOS 14.1-20171215-NIGHTLY-serranoltexx, Android 7.1.2):
![screenshot_20171221-172100](https://user-images.githubusercontent.com/63082/34264748-275400b8-e674-11e7-9656-8a22baa7a3b8.png)

Notice the broken keyboard cursor with blue background and the drop-down-arrow at TOTP overlapping the text at SHA-1. Other apps do not show this behaviour.

Also it appears as if the colours are generally a bit off: The keyboard cursor is usually dark blue.

**Comment by nilsbehlen** [comment]
thanks for your input, i will look into this tomorrow.
Can u tell me your screen resolution?

**Comment by devurandom** [comment]
[LineageOS wiki](https://wiki.lineageos.org/devices/serranoltexx) says: 540x960 (256 PPI)

**Comment by cornelinux** [comment]
@nilsbehlen I have the same behaviour on my galaxy S7 (Rsolution FHD) with default Android.

* Overlapping TYPE and ALGORITHM dropdowns.
* The cursor is a mixture of the blue square and the pink line/dot.

**Comment by nilsbehlen** [comment]
I fixed the background to be transparent.
The cursor color is still pink, should i make it blue?

**Comment by devurandom** [comment]
Confirming it is fixed. Thanks!

There could be a little bit larger gaps towards the screen edges as a minor improvement, since there is now a lot of space in the center of the screen. But it is already a lot better. ☺
