### ISSUE TITLE
Issuer name appears twice in description after scanning QR code

### ISSUE THREAD

**Issue by devurandom** [privacyidea/privacyidea-authenticator#27]
I scan a QR code like `otpauth://totp/ISSUER:USERNAME_OR_EMAIL?secret=s1xt33nnumb3rs4ndl3tt3rs&issuer=ISSUER` and privacyIDEA 0.1.5 adds it with the description `ISSUER: ISSUER:USERNAME_OR_EMAIL` -- the issuer name appears twice in the description. I would instead expect a description like `ISSUER: USERNAME_OR_EMAIL`.

**Comment by cornelinux** [comment]
Note: According to the Key Uri Spec the Issue can be seperated by either ":" or urlencoded "%3A".
https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer

The privacyIDEA server itself relies on the configuration of the administrator, what he wants to put in the LABEL field and in the ISSUER field. There are two policies to define the issuer and the tokenlabel:
1. http://privacyidea.readthedocs.io/en/latest/policies/enrollment.html#tokenissuer
2. http://privacyidea.readthedocs.io/en/latest/policies/enrollment.html#tokenlabel

No admin of a healthy mind would define:
A) tokenissuer = ISSUER
B) tokenlabel = ISSUER: LABEL

I.e. with privacyIDEA an administrator will not put the ISSUER into the label field.
Nevertheless to comply with the KEY Uri and to have the privacyIDEA Authenticator work nice with other services I recommend the following logic, which will also somehow match the key uri Spec:

1. If ``issuer=`` parameter is present, this will be the issuer! No matter what.
    1. if the ``label`` does not contain ":" or "%3A" fine. The label is the label. Do not modify.
    2. if the ``label`` contains a ":" or "%3A" and the part before the ":" is the same as the issuer parameter, we simply drop this part of the label and the colon, (since it is already contained in the issuer parameter).    
    3. if the ``label`` contains ":"/"%3A" and the part before the ":" is different from the issuer parameter, display the complete label. (Do not modify).
2. If the ``issuer`` parameter is not present, we split the ":"/"%3A" first part of the label as issuer.
3. If there is no ``issuer`` parameter and no ":"/"%3A" in the label, we have no issuer.

@nilsbehlen does this make sense to you?

# Examples

* ``otpauth://hotp/LABEL?secret=Q...P&counter=1&digits=6&issuer=ISSUER`` will result in ``issuer=ISSUER`` and ``label=LABEL``. (1.i)
* ``otpauth://hotp/ISSUER%3A%20LABEL?secret=Q...P&counter=1&digits=6&issuer=ISSUER`` will result in ``issuer=ISSUER`` and ``label= LABEL``. (1.ii)
*  ``otpauth://hotp/HANS%3A%20LABEL?secret=Q...P&counter=1&digits=6&issuer=ISSUER`` will result in ``issuer=ISSUER`` and ``label=HANS: LABEL``. (1.iii)
*  ``otpauth://hotp/ISSUER%3A%20LABEL?secret=Q...P&counter=1&digits=6`` will result in ``issuer=ISSUER`` and ``label= LABEL``. (2)
*  ``otpauth://hotp/LABEL?secret=Q...P&counter=1&digits=6`` will result in ``issuer=`` and ``label=LABEL``.  (3)

**Comment by nilsbehlen** [comment]
well that is how it is as of now.
i just added 1 line for the case that the label starts with the issuer (if issuer is present) so that its not doubled.
