### ISSUE TITLE
Add about dialog

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator#3]
We need to add an about dialog that contains contact information and displays the license.

**Comment by nilsbehlen** [comment]
There is now an about-dialog. The formatting and content is up for discussion

**Comment by cornelinux** [comment]
Please also add a version number to the about dialog!

**Comment by cornelinux** [comment]
The "Apache 2.0" license should not be located under the acknowledgments. 

Move the apache license above that.
Change it to:
"The privacyIDEA Authenticator is licensed under the Apache 2.0 license."

**Comment by nilsbehlen** [comment]
done. We can also include the whole License text in the app for each Acknowledgement, like in the google authenticator, but it takes more time to implement
