### ISSUE TITLE
PrivacyIDEA TOTP refresh issue

### ISSUE THREAD

**Issue by finalbeta** [privacyidea/privacyidea-authenticator#38]
Hello, I'm testing the PrivacyIDEA Authenticator (with PrivacyIDEA enterprise edition).

We are running this on two phones and we are both having the same issue. 
We have only one token inside the app. 
This token is a TOTP token. 
We do not close the app, but use the home button to go back to the main screen. 
X amount of minutes/seconds later, we go back to the app and we get exactly the same code. When this happens, when the progress bar reaches +-90%, a new code pops up. (that way we are sure something went wrong). 

This happens one every (5?) times.

I'm on a one plus X runnning CyanogenMod 13.0. (Android 6.0.1)
My collegue is on a One plus 5 running OxygenOS 5.1.1 (Android 8.1.0)

**Comment by nilsbehlen** [comment]
Hi,
thanks for your feedback!
I will look into this.
Just to be clear: the OTP code is still valid at all times? Is it just the animation of the progressbar that is not correct? or is the OTP invalid after going back in the app?

thanks alot

**Comment by finalbeta** [comment]
Hi, the OTP code is the same code that was displayed the last time we opened the application. 
So no, the code is not valid as it has expired a while back. 
The progres bar seems to function normally. But when it gets at 90?% the code refreshes. (at 100% the code refreshes again and this new code works).

**Comment by nilsbehlen** [comment]
hey, thanks again for your feedback. I updated the app and hope it fixes the problem for you too.

**Comment by finalbeta** [comment]
Hi Nils, I'm posting to confirm that this issue is solved. No need to keep this open any further. 
Normally we would have had the problem several thimes already, and we have not seen a bad TOTP code since the update. 

Thanks for the quick fix!
