### ISSUE TITLE
Add 2-step initialization

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator#4]
Add 2 step enrollment according to

https://github.com/privacyidea/privacyidea/wiki/concept%3A-SmartphoneApp

**Comment by nilsbehlen** [comment]
We have to make sure the phonepart of the secret (which has to be entered into PI) is available long enough to not get lost in the enrollmentprocess (e.g. by misclicking etc)
Also there should be a verfication with the first OTP that the enrollment was successful

**Comment by cornelinux** [comment]
The 2step enrollment parameters are defined here:

https://github.com/privacyidea/privacyidea/issues/797

**Comment by cornelinux** [comment]
I just checked and enrolling HOTP basically looks nice and verifies OTP correctly. 
I did not test all possible parameters, but only used the default values.

What do you think is still missing?

**Comment by cornelinux** [comment]
@nilsbehlen I think this is implemented and we can close the ticket. can we?

**Comment by nilsbehlen** [comment]
for the moment i think yes
