### ISSUE TITLE
Can we use a PIN to protect the tokens

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator#6]
We should be able to protect the token with a PIN.

This will be passed during enrollment, if the server requires to set a PIN.

**Comment by nilsbehlen** [comment]
Should it be like blocking the whole app with a pin or hide individual tokens and show them only if the pin is entered. need to discuss

**Comment by cornelinux** [comment]
If we pass it during the enrollment of a token, this will probably be a PIN per token.

**Comment by nilsbehlen** [comment]
Will the PIN be in the QR aswell or can the user set the PIN on the smartphone?

**Comment by nilsbehlen** [comment]
How long should the "unlocking" last for one token? (time or event when the token should be locked again)

**Comment by cornelinux** [comment]
# basic concept

* the QR code will contain the information, that the user needs to set a PIN for this token. We need to determine, how this information looks like, so that we do not polute/blow up the QR Code.
* I think the token should be locked when the token looses its focus. Then the user will have to enter the PIN again. Usually this would not matter, since a user gets an OTP value *once*. Then he gets it next day. So usually there will be no need to have the token unlocked for ten minutes. Simply have the token unlocked, as long as the user uses the App.

**Comment by nilsbehlen** [comment]
Its now possible to set a PIN for a token:
the queryparameter is **?pin=true**, if there should be no pin it can be left out.
But there are some things that need to be refined:

- change the input **keyboard to numbers** only

- make it possible to **delete a locked token** (?) Should that be possible?
(also there could be a queryparameter to make tokens undeleteable, would that be useful?)

- implement a **counter** for the tries of entering a PIN (with possibly a timeout or similar)

**Comment by nilsbehlen** [comment]
Also the PIN should be changable after it has been entered (=token is unlocked)
