### ISSUE TITLE
No User Feedback When privacyIDEA Server is Unreachable for Push Token

### ISSUE THREAD

**Issue by droobah** [privacyidea/privacyidea-authenticator#60]
Steps to recreate:
1. Ensure device is able to receive push requests from Firebase
2. Ensure device CANNOT reach the privacyIDEA server (this could be a problem in real world scenarios with a firewall/routing issue/load balancer issue)
3. Trigger challege for push token
4. Tap Approve

At this point /ttype/push cannot be reached so the approval fails.  However, there does not appear to be a message within the app to inform the user that the approval request failed.  It would also be useful if the attempt could be retried.

**Comment by nilsbehlen** [comment]
Hi, thanks for your feedback.
There should be a feedback that the authentication was unsuccessful in form of a small toast at the bottom, but i will check this scenario again.
Currently the app is not designed to retry authentication attempts, maybe that will be added in the future but we need to discuss that first.
