### ISSUE TITLE
Stop the app from crashing if keystore (operation) is unavailable

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea-authenticator#74]
The crash happens here:
https://github.com/privacyidea/privacyidea-authenticator/blob/62c7fca8ac5d887d8d150af712b9011654cb6c4e/app/src/main/java/it/netknights/piauthenticator/utils/SecretKeyWrapper.java#L146

could be caught here:
https://github.com/privacyidea/privacyidea-authenticator/blob/62c7fca8ac5d887d8d150af712b9011654cb6c4e/app/src/main/java/it/netknights/piauthenticator/utils/Util.java#L361

- Notify the user that the app cannot save tokens
(- Close the app?)

**Comment by nilsbehlen** [comment]
trace:

**java.security.InvalidKeyException: Keystore operation failed**
android.security.KeyStore.getInvalidKeyException(KeyStore.java:901)
android.security.KeyStore.getInvalidKeyException(KeyStore.java:926)
android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
t javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
javax.crypto.Cipher.chooseProvider(Cipher.java:773)
javax.crypto.Cipher.init(Cipher.java:1143)
javax.crypto.Cipher.init(Cipher.java:1084)
it.netknights.piauthenticator.utils.SecretKeyWrapper.unwrap(SecretKeyWrapper.java:146)
it.netknights.piauthenticator.utils.Util.getSecretKey(Util.java:553)
it.netknights.piauthenticator.utils.Util.saveToFile(Util.java:468)
it.netknights.piauthenticator.utils.Util.saveToFile(Util.java:490)
it.netknights.piauthenticator.utils.Util.saveTokens(Util.java:172)
it.netknights.piauthenticator.presenter.Presenter.saveTokenlist(Presenter.java:240)
it.netknights.piauthenticator.presenter.Presenter.onStop(Presenter.java:235)
it.netknights.piauthenticator.viewcontroller.MainActivity.onStop(MainActivity.java:435)
android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1433)

**Comment by timosturm** [comment]
This should be fixed in v2.0.2. The application checks if the saving of tokens works on startup. If not a dialog is shown, informing the user that the application cannot work without the keystore.

**Comment by nilsbehlen** [comment]
closed via #81
