### ISSUE TITLE
Pre-Select label when renaming

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea-authenticator#77]
Pre-Select label when renaming

**Comment by nilsbehlen** [comment]
maybe also open the keyboard.

**Comment by timosturm** [comment]
@nilsbehlen 

This may already be fixed in v2.0.2. Please double-check the corresponding branch. If the problem still persists please add more information about it.

**Comment by nilsbehlen** [comment]
closed via #81
