### ISSUE TITLE
Push notifications seem to be duplicated

### ISSUE THREAD

**Issue by droobah** [privacyidea/privacyidea-authenticator#88]
Push notification still pops up from notification bar even if app is in foreground.

If Allow is tapped from notification and the app is then launched, the Allow button is still there with the same push request.

This behavior was not in the previous release (2.0.1)

Tested on Samsung S7 running 7.0 [authenticator version 2.0.2b1]

**Comment by nilsbehlen** [comment]
The notification behavior is better now. Also when pressing allow in the notification it is broadcasted to the app (if running). The new version is already in rollout.
