### ISSUE TITLE
2step enrollment: modal dialog not modal

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator#90]
During 2step enrollment there is this dialog that displays the phone part of the secret key.
It has an OK button.

But clicking everywhere *outside* of the dialog also closes this dialog.

On smartphones that have a very quick screensaver, where the screen turns dark very quickly this leads to the following problem:
The user taps anywhere (outside) of the screen and the dialog will close. So there is not enough time to read and type the phone part.

The dialog should only close, when "OK" is tapped.
(The iOS App has the same issue)

**Comment by timosturm** [comment]
@cornelinux @nilsbehlen Wasn't this issue fixed in https://github.com/privacyidea/privacyidea-authenticator/pull/91 ?

**Comment by cornelinux** [comment]
I do not know. I just was told, that this was observed "in the wild" ca. 12 days ago. (From the app store)
So if #91 fixed this issue, it can be closed.

**Comment by nilsbehlen** [comment]
Yes it was, i typed 20 instead of 90 in the pr, my bad.
