### ISSUE TITLE
'Decline' of PUSH token in android app

### ISSUE THREAD

**Issue by MatthiasLaechele** [privacyidea/privacyidea-authenticator#96]
In most cases, the decline option is not showed if a PUSH token is sent to my mobile device.
If there are consecutive login attempts, the decline is shown eventually. I never see decline on the 1st hit.

Decline is missing in the app itself, only accept button is shown. 
It also missing as a link in the notification.

Device: Huawei P30, Android 10.0, privacyIDEA Authenticator 2.0.4b0

**Comment by nilsbehlen** [comment]
Hi, in v2.0.5. the dismiss button will be visible from the beginning, instead of when a failure occurs. The notification can be dismissed by swiping it away.
