### ISSUE TITLE
disable android screenshot feature and eventually other mobile platforms

### ISSUE THREAD

**Issue by derwenno** [privacyidea/privacyidea-authenticator#97]
Hello,
under android the screenshot feature can do screenshots from the pricacyidea tokens in the app.
some Malware can do in the background screenshots from your tokens.
Here the source:
https://www.golem.de/news/google-authenticator-2fa-codes-lassen-sich-einfach-abgreifen-2003-147119.html
Is there a plan to fix this security issue?
Best regards
Derwenno

**Comment by nilsbehlen** [comment]
Hi, this is fixed in version 2.0.5. which should be live soon.
